language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
env:
    - DJANGO_VERSION=">=1.8,<1.9"
    - DJANGO_VERSION=">=1.9,<1.10"
    - DJANGO_VERSION=">=1.10,<1.11"
install:
    - pip install coverage coveralls
    - pip install Django$DJANGO_VERSION
    - pip install .
script: coverage run runtests.py
after_success: coveralls
